# Generated by Django 4.0 on 2021-12-15 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerFromChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=70, verbose_name='Chat ID пользователя')),
                ('tg_login', models.CharField(max_length=70, verbose_name='Telegram логин пользователя')),
                ('name', models.CharField(max_length=150, verbose_name='Имя пользователь (ответ на первый вопрос)')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerToChoose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_one', models.BooleanField()),
                ('option_two', models.BooleanField()),
                ('option_three', models.BooleanField()),
                ('related_qwestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.answerfromchat')),
            ],
        ),
    ]
