# Generated by Django 4.0 on 2021-12-20 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_chatinuse_messageinchatinuse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageInChatInUse',
            new_name='MessageFromBotInChat',
        ),
    ]
