# Generated by Django 4.0 on 2021-12-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_rename_messageinchatinuse_messagefrombotinchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerfromchat',
            name='answers',
            field=models.CharField(default='option0', max_length=150, verbose_name='Ответы через запятую'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatinuse',
            name='presaved_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя пользователя (ответ на первый вопрос)'),
        ),
        migrations.AddField(
            model_name='chatinuse',
            name='presaved_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер телефона'),
        ),
        migrations.DeleteModel(
            name='AnswerToChoose',
        ),
    ]
